#!/bin/bash
if [ ! -f /boot/optional/plugins/rclone/rclone.conf ] ; then
  if [ ! -d /boot/optional/plugins/rclone ]; then
    mkdir -p /boot/optional/plugins/rclone
  fi
  touch /boot/optional/plugins/rclone/rclone.conf
fi

if [ -f /usr/bin/rcloneorig ] ; then
  exec /usr/bin/rcloneorig --config /boot/optional/plugins/rclone/rclone.conf "$@"
else
  echo "rclone not found, please visit the rclone Plugin page within the MOS WebUI"
  exit 1
fi
